include: package:lints/recommended.yaml

linter:
  rules:
    public_member_api_docs: false
    prefer_const_constructors: true
    prefer_single_quotes: true
analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
